#!/usr/bin/ansible-playbook
---
 - name: checking monitoring commands
   hosts: all
   tasks:
        - name: uptime of the server
          command: uptime
          register: up
        - debug: 
                var: up.stdout
                verbosity: 4

        - name: kernel version of the server
          command: uname -a
          register: ker
        - debug: var=ker.stdout
        
        - name: mounted fs info
          command: df -h
          register: df
        - debug: var=df.stdout_lines

        - name: date of the server
          command: date
          register: date
        - debug: var=date.stdout
